<?php

if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group(array(
        'key' => 'group_640a1efed6a99',
        'title' => 'Yes& Pre-Footer Block',
        'fields' => array(
//            array(
//                'key' => 'field_640a20e1ef0ff',
//                'label' => 'Footer Block Image',
//                'name' => 'footer_block_image',
//                'aria-label' => '',
//                'type' => 'image',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'return_format' => 'array',
//                'library' => 'all',
//                'min_width' => '',
//                'min_height' => '',
//                'min_size' => '',
//                'max_width' => '',
//                'max_height' => '',
//                'max_size' => '',
//                'mime_types' => '',
//                'preview_size' => 'medium',
//            ),
            array(
                'key' => 'field_6407975a0826b_yfb',
                'label' => 'Sub-heading text',
                'name' => 'sub-heading_text_yfb',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6407c33fc31fd_yfb',
                'label' => 'Sub-heading text color',
                'name' => 'sub-heading_text_color_palette_yfb',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#FFFFFF',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ),
            array(
                'key' => 'field_6407c371c31fe_yfb',
                'label' => 'Sub-heading text background color',
                'name' => 'sub-heading_text_background_color_yfb',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '#c10330' => 'Red',
                    '#000000' => 'Black',
                    '#ffbf00' => 'Yellow',
                ),
                'default_value' => '#c10330',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6407c50d9233d_yfb',
                'label' => 'Heading text',
                'name' => 'heading_text_yfb',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => 50,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6407c51e9233e_yfb',
                'label' => 'Heading text color',
                'name' => 'heading_text_color_yfb',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ),
            array(
                'key' => 'field_6407c56c2409a_yfb',
                'label' => 'Yes& heading alignment options',
                'name' => 'alignment_options_yfb',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Left',
                    'right' => 'Right',
                    'center' => 'Center',
                ),
                'default_value' => 'left',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6407c62efc9e5_yfb',
                'label' => 'Decorative circles',
                'name' => 'include_decorative_circles_yfb',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Include',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
//            array(
//                'key' => 'field_640a2146f1ccc_yfb',
//                'label' => 'Button Alignment',
//                'name' => 'yesand_button_alignment_yfb',
//                'aria-label' => '',
//                'type' => 'select',
//                'instructions' => '',
//                'required' => 0,
//                'conditional_logic' => 0,
//                'wrapper' => array(
//                    'width' => '',
//                    'class' => '',
//                    'id' => '',
//                ),
//                'choices' => array(
//                    'left' => 'Left',
//                    'right' => 'Right',
//                    'center' => 'Center',
//                ),
//                'default_value' => 'left',
//                'return_format' => 'value',
//                'multiple' => 0,
//                'allow_null' => 0,
//                'ui' => 0,
//                'ajax' => 0,
//                'placeholder' => '',
//            ),
            array(
                'key' => 'field_640a21d0b2428_yfb',
                'label' => 'Button sub-heading text (Italics)',
                'name' => 'yesand_button_sub-heading_text_yfb',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_640a2223b2429_yfb',
                'label' => 'Link(text, url, target)',
                'name' => 'yesand_link_yfb',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/yes-footer-block',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;
?>