<?php
if ( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_642ab757413b1',
	'title' => 'Yes& Accordion Block',
	'fields' => array(
		array(
			'key' => 'field_642ac01b83eb7',
			'label' => 'Accordion Tabs',
			'name' => 'accordion_tabs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_642ab75953592',
					'label' => 'Accordion Item',
					'name' => '',
					'aria-label' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'parent_repeater' => 'field_642ac01b83eb7',
				),
				array(
					'key' => 'field_642ac18817a14',
					'label' => 'Accordion Content',
					'name' => 'accordion_content',
					'aria-label' => '',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layouts' => array(
						'layout_642ac19944833' => array(
							'key' => 'layout_642ac19944833',
							'name' => 'wysiwyg',
							'label' => 'Wysiwyg',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_642ac1cc17a15',
									'label' => 'Title Accordion Item (Wysiwyg)',
									'name' => 'title_accordion_item_wysiwyg',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => 160,
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_642ac1e217a16',
									'label' => 'Content Wysiwyg',
									'name' => 'content_wysiwyg',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
						),
						'layout_642ac559e2a26' => array(
							'key' => 'layout_642ac559e2a26',
							'name' => 'jobs_accordion_item',
							'label' => 'Jobs accordion item',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_642c30925deff',
									'label' => 'Title Accordion Item (Jobs)',
									'name' => 'title_accordion_item_jobs',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_642c30a65df00',
									'label' => 'Job Item',
									'name' => 'job_item',
									'aria-label' => '',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'row',
									'min' => 0,
									'max' => 0,
									'collapsed' => '',
									'button_label' => 'Add Row',
									'rows_per_page' => 20,
									'sub_fields' => array(
										array(
											'key' => 'field_642ac59ce2a28',
											'label' => 'Position Title',
											'name' => 'position_title',
											'aria-label' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'maxlength' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'parent_repeater' => 'field_642c30a65df00',
										),
										array(
											'key' => 'field_642ac5b7e2a29',
											'label' => 'Position Content',
											'name' => 'position_content',
											'aria-label' => '',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
											'delay' => 0,
											'parent_repeater' => 'field_642c30a65df00',
										),
										array(
											'key' => 'field_642ac5c4e2a2a',
											'label' => 'Read more link',
											'name' => 'read_more_link',
											'aria-label' => '',
											'type' => 'link',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'return_format' => 'array',
											'parent_repeater' => 'field_642c30a65df00',
										),
									),
								),
							),
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
					'button_label' => 'Add Row',
					'parent_repeater' => 'field_642ac01b83eb7',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/yes-accordion-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;
?>