<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_63eab7451d32b',
        'title' => 'Social Media',
        'fields' => array(
            array(
                'key' => 'field_instagram_yes',
                'label' => 'Instagram Link',
                'name' => 'instagram_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_youtube_yes',
                'label' => 'YouTube Link',
                'name' => 'youtube_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_vimeo_yes',
                'label' => 'Vimeo Link',
                'name' => 'vimeo_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_facebook_yes',
                'label' => 'Facebook Link',
                'name' => 'facebook_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_twitter_yes',
                'label' => 'Twitter Link',
                'name' => 'twitter_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_linkedin_yes',
                'label' => 'LinkedIn Link',
                'name' => 'linkedin_link',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Leave the field blank to not show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;