<?php

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_640f3c4b15885',
        'title' => 'Yes& Homepage Slider',
        'fields' => array(
            array(
                'key' => 'field_640f3c4c70a7b',
                'label' => 'Slide',
                'name' => 'home_page_slide',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'row',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Add Row',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6407c371c3stp_hps',
                        'label' => 'Slide Type',
                        'name' => 'slide-type',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'slide-type-1' => 'Type 1',
                            'slide-type-2' => 'Type 2',
                            'slide-type-3' => 'Type 3',
                        ),
                        'default_value' => 'slide-type-1',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_640f3c8870a7c',
                        'label' => 'Media',
                        'name' => 'media_hps',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_6407975a0826b_hps',
                        'label' => 'Sub-heading text',
                        'name' => 'sub-heading_text_hps',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_6407c33fc31fd_hps',
                        'label' => 'Sub-heading text color',
                        'name' => 'sub-heading_text_color_palette_hps',
                        'aria-label' => '',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#FFFFFF',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_6407c371c31fe_hps',
                        'label' => 'Sub-heading text background color',
                        'name' => 'sub-heading_text_background_color_hps',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            '#c10330' => 'Red',
                            '#000000' => 'Black',
                            '#ffbf00' => 'Yellow',
                        ),
                        'default_value' => '#c10330',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_6407c50d9233d_hps',
                        'label' => 'Heading text',
                        'name' => 'heading_text_hps',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => 50,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_6407c51e9233e_hps',
                        'label' => 'Heading text color',
                        'name' => 'heading_text_color_hps',
                        'aria-label' => '',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#000000',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_640f3ce370a7d',
                        'label' => 'Tags',
                        'name' => 'tags_hps',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => 50,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_640f3fefe1dd8',
                        'label' => 'Text',
                        'name' => 'text_hps',
                        'aria-label' => '',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_640f4003e1dd9',
                        'label' => 'Link',
                        'name' => 'link_hps',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                    array(
                        'key' => 'field_640f4003e1dd9_hps',
                        'label' => 'Color of link',
                        'name' => 'color_link_hps',
                        'aria-label' => '',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '#c10330',
                        'enable_opacity' => 0,
                        'return_format' => 'string',
                        'parent_repeater' => 'field_640f3c4c70a7b',
                    ),
                ),
            ),
        ),
        'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/yes-homepage-slider',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
    ));

endif;
?>